# Site settings
title: Mi cuaderno
email: israelrevert@gmail.com
description: "Yet another blog/site with mainly technical stuff.  I write mainly about technology, software, programming, and randomly about other stuff."
baseurl: ""
url: "http://irevert.github.com"

# Build settings
markdown: kramdown
permalink: pretty

collections:
  articles:
    output: true
